//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36301
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class HandlerBean
{
	private int handlerNumber;
	private string handlerClass;

	public int HandlerNumber {
		get{ return this.handlerNumber; }
		set{ this.handlerNumber = value; }
	}

	public string HandlerClass { 
		get{ return this.handlerClass; }
		set{ this.handlerClass = value; }
	}



}
